### ISSUE TITLE
Neerslag card not visible on mobile app HA

### ISSUE THREAD

**Issue by Jurgenn22** [aex351/home-assistant-neerslag-app#17]
Not visible on Official mobile app Home Assistant for Android. 
Shows: custom element doesn't exist: neerslag-card.

**Comment by Jurgenn22** [comment]
> That message means that the Neerslag Card has not been loaded in your Home Assistant. Is the Neerslag Card working for you in a browser? if yes, then please restart your mobile app and clear the mobile cache. If no, then please ensure the Neerslag App is installed in Home Assistant, restart Home Assistant and clear your browser/app cache.

App stopped, cleared cache, turned wifi off and on. Still not working. Works on a MacBook with Chrome browser.

**Comment by aex351** [comment]
If it works on your laptop than I see no reason why it should not work in the app. Because the Home Assistant app basically just loads the front-end.  It works more less like a mobile browser. You can double check to see if the Neerslag Card works on different browser, including a mobile browser too. 

If that also is working fine, then I think the problem is with the Home Assistant app itself. Other users have reported similar issues in the past. It always boils down to clearing the cache. In your case, that also seems to be not working. I would then suggest to reinstall the app, but only after you confirmed that the Neerslag Card is working fine in other browsers too. 

Also just as a note, there is the Neerslag App package (includes the Neerslag Card) and the Neerslag Card package. Make sure to have only one installed.

**Comment by Jurgenn22** [comment]
> If it works on your laptop than I see no reason why it should not work in the app. Because the Home Assistant app basically just loads the front-end. It works more less like a mobile browser. You can double check to see if the Neerslag Card works on different browser, including a mobile browser too.
> 
> If that also is working fine, then I think the problem is with the Home Assistant app itself. Other users have reported similar issues in the past. It always boils down to clearing the cache. In your case, that also seems to be not working. I would then suggest to reinstall the app, but only after you confirmed that the Neerslag Card is working fine in other browsers too.
> 
> Also just as a note, there is the Neerslag App package (includes the Neerslag Card) and the Neerslag Card package. Make sure to have only one installed.

Success, I extracted the neerslag card from custom components, put it in the www folder, added source to config.yaml, and it now works in the ha app as well.

**Comment by aex351** [comment]
The Neerslag App works isolated and does not make use of the www folder.  While copying the front-end card to the www folder will work, because of how Home Assistant works, it will mean that it won't be automatically updated with any future Neerslag App updates. So for each and every Neerslag App update you will need to do this again. 

I would suggest to install the Neerslag App as per the instructions in the readme.

**Comment by Jurgenn22** [comment]
> The Neerslag App works isolated and does not make use of the www folder. While copying the front-end card to the www folder will work, because of how Home Assistant works, it will mean that it won't be automatically updated with any future Neerslag App updates. So for each and every Neerslag App update you will need to do this again.
> 
> I would suggest to install the Neerslag App as per the instructions in the readme.

Removed everything, reinstalled the app, but same problem on the ha app. I give up.

**Comment by aex351** [comment]
Can you share the log files? Maybe something can be seen from that.

I also just reinstalled the Home Assistant app on an Android phone and I can detect no issue. So I am really curious to know what the issue could be on your end. It must be something related to the Home Assistant app on your device. Because like you said. It works for you in various browsers and mobile browser right?

**Comment by Jurgenn22** [comment]
> Can you share the log files? Maybe something can be seen from that.
> 
> I also just reinstalled the Home Assistant app on an Android phone and I can detect no issue. So I am really curious to know what the issue could be on your end. It must be something related to the Home Assistant app on your device. Because like you said. It works for you in various browsers and mobile browser right?

I reinstalled the ha app and now it works.
