### ISSUE TITLE
type: 'custom:neerslag-card' not found after longer time

### ISSUE THREAD

**Issue by pvmil** [aex351/home-assistant-neerslag-app#2]
Dear AEX351, 

To start off: I really like the app, very nice! Installation via HACS was easy
The thing I experience is that when I run this on my tablet, after some time I get a red box reporting 'custom:neerslag-card' is not found. Reloading the page fixes this. Is this an issue on my side?
I used to have the neerslag card package installed seperately, but removed that from HACS

**Comment by aex351** [comment]
Thanks for your feedback. Much appreciated.

The issue with the card not found is a known issue to me. I'm looking for a way to fix it. A current workaround is to reload your dashboard.

Regarding the other small remark. That will be a feature or enhancement request. It could be picked up in the future once the Neerslag App had become more stable.

**Comment by pvmil** [comment]
I've removed the feature enhancement and created a separate ticket out of this. Indeed something for a future release, stability first.
Can I help out in gathering more information to fix the card-not-found issue?

**Comment by aex351** [comment]
Sure you can. What would be helpful is to monitor the issue and describe when this occurs.

I have re-applied a fix/workaround (for the Neerslag App) which I had in an earlier version of the Neerslag Card. The card will now load a bit slower (2000 ms). So that should fix the issue with the card not being loaded correctly. What you probably also observe is that with this fix/workaround you can now see the light/medium/heavy rain labels again.

**Comment by aex351** [comment]
Applied a permanent fix for the card not found error. The previous fix/workaround is still present as it fixes the rain labels. Let me know if you are still experiencing this issue.

**Comment by pvmil** [comment]
I'm not experiencing the card-not-found issue anymore. Thanks a lot!
We use the neerslag-card multiple times per day looking at in on the front page of the tablet interface running permanently in the kitchen.
