### ISSUE TITLE
where to change color graph line

### ISSUE THREAD

**Issue by LRvdLinden** [aex351/home-assistant-neerslag-app#6]
Hi, where can I change the color of the graph line?

**Comment by aex351** [comment]
Currently there is no option to change the colors. The only way to change the colors is to modify the code.

**Comment by LRvdLinden** [comment]
I was searching in the code and have seen some RGBA colors. After changing that nothing happens

**Comment by aex351** [comment]
You can make the changes to `neerslag-card.js`. That should work. Make sure to refresh your browser. In the same directory there could also be a `.gz` file. HACS generates that. The Neerslag App doesn't use it, but if the browser refresh doesn't help you can also try to delete that file to see if that helps. As a note: any changes you make are lost when you update the Neerslag App.

**Comment by LRvdLinden** [comment]
Refresh heeft niet geholpen. Hmmm

**Comment by LRvdLinden** [comment]
I have change rgba in to rgb on line 434 and 438. Reboot ha and clear cash. Nothing change. Also changes all the icons. Also noting happend. ![image](https://user-images.githubusercontent.com/77990847/117562990-201f1d80-b0a3-11eb-834a-0154fc6291d6.jpeg)![image](https://user-images.githubusercontent.com/77990847/117562992-23b2a480-b0a3-11eb-960f-42cb244e31cf.png)

**Comment by aex351** [comment]
Maybe you have both the `neerslag-app` and the `neerslag-card` installed? There is no other reason, besides some caching mechanism, I can think of why the changes you make are not reflected.

**Comment by LRvdLinden** [comment]
Yes i have both. Do i need to delete the card?

**Comment by aex351** [comment]
Correct, if you have installed the `neerslag-app` you should uninstall the `neerslag-card`. Because the `neerslag-app` contains the `neerslag-card`. If you install both separately, then depending on the inner workings of Home Assistant one or the other gets loaded. If you open the developer console you will probably see an error message which states that the particular card cannot be loaded again. In your current case, you are making changes to a file that actually never gets loaded.

In the readme file of the `neerslag-app` there is a big note stating to uninstall the `neerslag-card` package before using the `neerslag-app` package. Make sure to also remove the custom sensors.

> This package contains the Neerslag Card. Make sure to uninstall this from Home Assistant before using the Neerslag App, to avoid unexpected behaviour. This includes manually removing the custom sensors.

**Comment by LRvdLinden** [comment]
Super man! Dankje! Thanks a lot!

**Comment by LRvdLinden** [comment]
It works here!

![image](https://user-images.githubusercontent.com/77990847/138165205-bfc6e462-6d32-4c8d-9a2d-86a25fd31966.jpeg)

**Comment by aex351** [comment]
@LRvdLinden, did you modify the graph configuration (Chart.js) yourself? 

Because I see in your screenshot that the graph is not rendered correctly: 
- There is a legend visible (Buienalarm and Buienradar);
- The line in the graph contains dots;
- There is no light/medium/heavy rain indication visible.

This is similar to the issue as reported here: https://github.com/aex351/home-assistant-neerslag-app/issues/18. This is caused by some other component / custom integration that is overriding the configuration of the `neerslag-card`. I have not found the solution yet or the actual root cause as to how other components are able to do this. Another user found that his problem was caused by the `lovelace-buien-rain-card`: https://github.com/aex351/home-assistant-neerslag-app/issues/18#issuecomment-926674226. Removing it resolved his issue.

**Comment by LRvdLinden** [comment]
I installed the app again and still have this issue. Maby it is made by the dashboard i used. Dwains Dashboard.

![image](https://user-images.githubusercontent.com/77990847/138323909-97224620-62e3-4caf-a0e0-ee2a30ad0767.png)
